### ISSUE TITLE
Automatic builds seem to deploy latest updated branch rather than master branch only.

### ISSUE THREAD

**Issue by gsrohde** [PecanProject/betydbdoc-dataentry#5]
@robkooper I noticed that https://pecanproject.github.io/bety-documentation/dataentry/ was showing the text from the `metadata_entry` branch.  To test my theory, I made a minor change to the `master` branch.  Now the master branch text is being shown instead.

**Comment by robkooper** [comment]
fixed in #6 this should probably be put on all other repos as well.

**Comment by gsrohde** [comment]
@robkooper The deployment step is failing.  The only reason the Travis test passed on your branch is that it skips deployment for all but the master branch.

**Comment by robkooper** [comment]
fixed now
